# -*- coding: utf-8 -*-
"""KNN_PredictDiabetes_Pratham.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LW29izhs6--FyjUC7Ehdn9z5w1ZyI9UU
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

from google.colab import drive
drive.mount('/content/gdrive')
root_path = 'gdrive/My Drive/'

dataset = pd.read_csv('gdrive/My Drive/diabetes.csv')

len(dataset)

dataset.head()

X = dataset.iloc[:, 0:8]
y = dataset.iloc[:, 8]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, test_size=0.2)

print(len(X_train))
print(len(y_train))
print(len(X_test))
print(len(y_test))

classifier = KNeighborsClassifier(n_neighbors=11, p=2,metric='euclidean')

classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)
y_pred

print(accuracy_score(y_test, y_pred))